spring.application.name=caja-ahorros

spring.datasource.url=jdbc:postgresql://${DATABASE_URL:postgresql://localhost:5432/ahorros_db}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:10000}